#include "uriparser.h"
#include <stdio.h>
#include <assert.h>
#include <string.h>
#include <stdbool.h>

int main(void)
{
    struct uri uri = {0};
    bool rc = false;

    printf("case 1\n");
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 2\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 3\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 4\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 5\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 6\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 7\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 8\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 9\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 10\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 11\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 12\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 13\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 14\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 15\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 16\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@localhost");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 17\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 18\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 19\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 20\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 21\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 22\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 23\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 24\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 25\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 26\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 27\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 28\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 29\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 30\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root:e4D8F6z3f2b1@127.0.0.1?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 31\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root:e4D8F6z3f2b1@127.0.0.1#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 32\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root:e4D8F6z3f2b1@127.0.0.1");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(0 == strcmp("e4D8F6z3f2b1", uri.password));
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);


    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 50\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 51\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 52\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 53\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 54\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 55\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 56\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 57\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 58\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 59\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 60\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 61\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 62\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 63\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 64\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@localhost");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 65\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 66\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 67\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 68\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 69\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 70\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 71\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 72\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 73\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 74\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 75\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 76\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 77\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://root@127.0.0.1?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 78\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 79\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 80\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://root@127.0.0.1");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(0 == strcmp("root", uri.username));
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 98\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 99\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 100\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 101\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 102\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 103\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 104\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 105\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 106\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 107\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 108\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 109\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 110\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 111\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 112\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://localhost");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("localhost", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 113\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 114\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 115\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 116\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 117\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 118\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 119\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri,"mysql://127.0.0.1:3306#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 120\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1:3306");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(0 == strcmp("3306", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 121\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1/account?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 122\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1/account?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 123\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1/account#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 124\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1/account");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(0 == strcmp("account", uri.path));
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 125\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1?charset=utf8mb4#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 126\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1?charset=utf8mb4");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(0 == strcmp("charset=utf8mb4", uri.query));
    assert(NULL == uri.fragment);

    printf("case 127\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1#debug");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(0 == strcmp("debug", uri.fragment));

    printf("case 128\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql://127.0.0.1");
    assert(true == rc);
    assert(0 == strcmp("mysql", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("127.0.0.1", uri.host));
    assert(NULL == uri.port);
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);


    printf("case 145\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "unix:///var/run/docker.sock");
    assert(false == rc);

    printf("case 146\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:/account?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 147\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:/account?charset=utf8mb4");
    assert(false == rc);

    printf("case 148\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:/account#debug");
    assert(false == rc);

    printf("case 149\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:/account");
    assert(false == rc);

    printf("case 150\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 151\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:?charset=utf8mb4");
    assert(false == rc);

    printf("case 152\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:#debug");
    assert(false == rc);

    printf("case 153\n");
    bzero(&uri, sizeof(struct uri));
    rc = uri_parse(&uri, "mysql:");
    assert(false == rc);

    printf("case 154\n");
    rc = uri_parse(&uri, "mysql:root:e4D8F6z3f2b1@localhost:3306/account?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 155\n");
    rc = uri_parse(&uri, "http://devws.google.com:80");
    assert(true == rc);
    assert(0 == strcmp("http", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("devws.google.com", uri.host));
    assert(0 == strcmp("80", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 156\n");
    rc = uri_parse(&uri, "git+ssh://devws.google.com:80");
    assert(true == rc);
    assert(0 == strcmp("git+ssh", uri.scheme));
    assert(NULL == uri.username);
    assert(NULL == uri.password);
    assert(0 == strcmp("devws.google.com", uri.host));
    assert(0 == strcmp("80", uri.port));
    assert(NULL == uri.path);
    assert(NULL == uri.query);
    assert(NULL == uri.fragment);

    printf("case 157\n");
    rc = uri_parse(&uri, "git+ssh:///account?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 158\n");
    rc = uri_parse(&uri, "git+ssh://@/account?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 159\n");
    rc = uri_parse(&uri, "git+ssh://root:e4D8F6z3f2b1@/account?charset=utf8mb4#debug");
    assert(false == rc);

    printf("case 160\n");
    rc = uri_parse(&uri, "git+ssh://@localhost:3306/account?charset=utf8mb4#debug");
    assert(false == rc);

}
